// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdT1wKSrnEfdzekIyD1WArmfz9fwQwnj4',
    appId: '1:977814785059:web:058926047ddb2a27cff596',
    messagingSenderId: '977814785059',
    projectId: 'chat-app04-52052',
    authDomain: 'chat-app04-52052.firebaseapp.com',
    storageBucket: 'chat-app04-52052.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKm5xHNgXasqn21Zwzp-WgnXnh3JOu_ME',
    appId: '1:977814785059:android:5e236e7bddadeb68cff596',
    messagingSenderId: '977814785059',
    projectId: 'chat-app04-52052',
    storageBucket: 'chat-app04-52052.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuXF6edfpFmNcU7dyRKDZlURjQeQ9gHV0',
    appId: '1:977814785059:ios:89a58d4ca566fb67cff596',
    messagingSenderId: '977814785059',
    projectId: 'chat-app04-52052',
    storageBucket: 'chat-app04-52052.appspot.com',
    iosBundleId: 'com.example.chatApp04',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuXF6edfpFmNcU7dyRKDZlURjQeQ9gHV0',
    appId: '1:977814785059:ios:89a58d4ca566fb67cff596',
    messagingSenderId: '977814785059',
    projectId: 'chat-app04-52052',
    storageBucket: 'chat-app04-52052.appspot.com',
    iosBundleId: 'com.example.chatApp04',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdT1wKSrnEfdzekIyD1WArmfz9fwQwnj4',
    appId: '1:977814785059:web:fc9f866aa39a9a2fcff596',
    messagingSenderId: '977814785059',
    projectId: 'chat-app04-52052',
    authDomain: 'chat-app04-52052.firebaseapp.com',
    storageBucket: 'chat-app04-52052.appspot.com',
  );
}
